### ISSUE TITLE
mixed models

### ISSUE THREAD

**Issue by bowlerbear** [coreytcallaghan/intra_specific_urban_tolerance#7]
while cycling home, i wonder whether the following little analysis might be useful:

buffer/species-specific urban tolerances ~ (1|Species) + (1|Buffer)
# the species random effect would estimate the inter-specific variation
# the buffer random effect would estimate the variance explained by the environment
# the residual would be the leftover intraspecific variance

I like this because we would have 3 variance (or sd estimates) which could be compared.

**Comment by bowlerbear** [comment]
sorry, dont know why I am shouting with the font!!!

**Comment by coreytcallaghan** [comment]
Ha. Yeah, okay. I like it.

I have half of this with the little trait based thing I did. So just need to add a random effect for species and remove traits as fixed effect!

**Comment by coreytcallaghan** [comment]
Sorry - I couldn't get to this until this morning. But I think I see what you are after.

So here is a model result for the 'adjusted urban tolerance' (how I currently calculate it):
![image](https://user-images.githubusercontent.com/28123686/139367862-6cc8f17b-2de6-49ff-8823-1671f07d0b19.png)

And the same model, but for the 'unadjusted urban tolerance' (not subtracting by the median of samples/environment):
![image](https://user-images.githubusercontent.com/28123686/139368371-aaec6ed6-710c-4f81-b24d-660cc3e01fa4.png)

**Comment by coreytcallaghan** [comment]
I guess this is one more line of support that indeed, interspecific variation is much greater than environmental variation and greater than intraspecific variation, but that intraspecific variation is greater than environmental variation as well.

Do you see this just as basically one additional line in the methods and then one additional line in the results.

The two different urban tolerance approaches are also more-or-less similar which is nice...

If you want to play with the models further, you can try this:

```
# prelim EDA
# packages
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggplot2)
library(tibble)
library(readr)

source("R/global_functions.R")

files <- list.files("random_polygon_results/500_km")

# summarize data function
aggregate_data_500 <- function(file_name){
  
  dat <- readRDS(paste0("random_polygon_results/500_km/", file_name)) %>%
    mutate(sample=gsub("random_sample_", "", file_name)) %>%
    mutate(sample=gsub(".RDS", "", sample))
  
  return(dat)
  
}

data_500_km_all <- bind_rows(lapply(files, aggregate_data_500))


hist(data_500_km_all$UT_median)
ut_adjusted_mod <- lme4::lmer(UT_median ~ (1|COMMON_NAME) + (1|sample), data=data_500_km_all)
summary(ut_adjusted_mod)

hist(data_500_km_all$median_viirs)
hist(log10(data_500_km_all$median_viirs))
ut_unadjusted_mod <- lme4::lmer(log10(median_viirs) ~ (1|COMMON_NAME) + (1|sample), data=data_500_km_all)
summary(ut_unadjusted_mod)

```

**Comment by bowlerbear** [comment]
yeah. nice!

I don't see this as much. But I like to also present numbers that mean something. And these sd will be easy to interpret by most people.
It is highlighting a lot of variability beyond species-level.

**Comment by coreytcallaghan** [comment]
Sweet. I'll try to work a sentence or two into the next version and then
highlight for you to have a look at.

Good idea though. Adds one more line of evidence for the overall message!
